Repository google/http_pattern_matcher, pull requests merged in 2021-03, with the labels that each got.

#6 Add a very simple fuzz test for HttpTemplate::Parse (#56)
  .bazelrc
  BUILD
  README.md
  WORKSPACE
  test/http_template_fuzz_test.cc
  test/http_template_fuzz_test_corpus/literal
  test/http_template_fuzz_test_corpus/path-double-wildcard
  test/http_template_fuzz_test_corpus/path-double-wildcard-capture
  test/http_template_fuzz_test_corpus/path-wildcard
  test/http_template_fuzz_test_corpus/path-wildcard-capture
Labels: approved, lgtm, size/M

#8 Make CI script executable
  script/ci.sh
Labels: approved, lgtm, size/XS

#10 Setup OSS Fuzz integration
  .bazelrc
Labels: approved, lgtm, size/M

#9 Add required root files
  .bazelversion
  SECURITY.md
Labels: approved, lgtm, size/S
